if(!settings.multipleView)
 settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="summary-4";
if(settings.render < 0) settings.render=4;
settings.inlineimage=true;
settings.embed=true;
settings.outformat="";
settings.toolbar=false;
viewportmargin=(2,2);

size (6cm);
import math;
import hyperbolic_geometry;
unitsize(3cm);
hyperbolic_point A = hyperbolic_point(0,0);
hyperbolic_point B = hyperbolic_point(2.7, 63);
hyperbolic_point C = hyperbolic_point(1.7, 13);
hyperbolic_point D = basepoint(hyperbolic_line(B,C), A);
hyperbolic_point E = basepoint(hyperbolic_line(C,A), B);
hyperbolic_point F = basepoint(hyperbolic_line(A,B), C);
hyperbolic_point P = mirror(hyperbolic_line(A,B), D);
hyperbolic_point Q = mirror(hyperbolic_line(A,C), D);
draw(unitcircle);
draw(hyperbolic_segment(A,B));
draw(hyperbolic_segment(A,C));
draw(hyperbolic_segment(B,C));
draw(hyperbolic_segment(A,D));
draw(hyperbolic_segment(P,Q));
draw(hyperbolic_segment(D,E));
draw(hyperbolic_segment(F,D));
draw(hyperbolic_segment(A,Q));
draw(hyperbolic_segment(A,P));
pen p = fontsize(1);
label("$A$",A.get_euclidean(),SW,p);
label("$B$",B.get_euclidean(),NE,p);
label("$C$",C.get_euclidean(),NE,p);
label("$D$",D.get_euclidean(),NE,p);
label("$E$",E.get_euclidean(),SW,p);
label("$F$",F.get_euclidean(),W,p);
label("$P$",P.get_euclidean(),NE,p);
label("$Q$",Q.get_euclidean(),NE,p);
path frame = (-0.3,-0.3)--(-0.3,1.1)--(1.1, 1.1)--(1.1,-0.3)--cycle;
clip(frame);
viewportsize=(345.0pt,0);
